"""empty message

Revision ID: 1bd26df602e8
Revises: edc475a4ddf6
Create Date: 2023-04-08 06:31:49.362511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bd26df602e8'
down_revision = 'edc475a4ddf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_users')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Email', sa.String(), nullable=False, server_default=''))
        batch_op.create_unique_constraint("uq_user_Email", ['Email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint("uq_user_Email", type_='unique')
        batch_op.drop_column('Email')

    op.create_table('_alembic_tmp_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('firstName', sa.VARCHAR(length=80), nullable=False),
    sa.Column('lastName', sa.VARCHAR(length=80), nullable=False),
    sa.Column('pwd', sa.VARCHAR(length=80), nullable=False),
    sa.Column('userName', sa.VARCHAR(length=80), nullable=False),
    sa.Column('Email', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Email', name='Email'),
    sa.UniqueConstraint('userName')
    )
    # ### end Alembic commands ###
