"""empty message

Revision ID: edc475a4ddf6
Revises: 
Create Date: 2023-04-06 05:53:21.687691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edc475a4ddf6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pnr', sa.String(length=10), nullable=False),
    sa.Column('origin', sa.String(length=4), nullable=False),
    sa.Column('destination', sa.String(length=4), nullable=False),
    sa.Column('flightTime', sa.Date(), nullable=False),
    sa.Column('basicFare', sa.Float(precision=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pnr')
    )
    op.create_table('usercred',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(), nullable=False),
    sa.Column('pwd', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userName')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=80), nullable=False),
    sa.Column('lastName', sa.String(length=80), nullable=False),
    sa.Column('pwd', sa.String(length=80), nullable=False),
    sa.Column('userName', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userName')
    )
    op.create_table('passengers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=80), nullable=False),
    sa.Column('lastName', sa.String(length=80), nullable=False),
    sa.Column('seatNum', sa.String(length=4), nullable=True),
    sa.Column('amtPaid', sa.Float(precision=2), nullable=True),
    sa.Column('pnr', sa.String(length=10), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seatNum', sa.String(length=4), nullable=False),
    sa.Column('seatPrice', sa.Float(precision=2), nullable=False),
    sa.Column('seatType', sa.String(length=20), nullable=False),
    sa.Column('flightId', sa.Integer(), nullable=False),
    sa.Column('passengerId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flightId'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['passengerId'], ['passengers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seatNum')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seats')
    op.drop_table('passengers')
    op.drop_table('users')
    op.drop_table('usercred')
    op.drop_table('flights')
    op.drop_table('blocklist')
    # ### end Alembic commands ###
